### ISSUE TITLE
Title not positioned correctly

### ISSUE THREAD

**Issue by BalestraPatrick** [prscX/react-native-about-libraries#2]
Hey there! I tried integrating the library in my project but I encountered an issue in adding some libraries with a longer title as you can see from the following screenshot.

Is this a bug in the library?

<img width="559" alt="screen shot 2018-03-04 at 8 39 20 pm" src="https://user-images.githubusercontent.com/3658887/36949695-3da37b3a-1fec-11e8-80cd-763755c23804.png">

**Comment by prscX** [comment]
Thanks @BalestraPatrick for raising the issue.

I have fixed the root cause, basically it was minor header styling issue in `Library.style.js` file. Can you please download latest V0.0.3 and verify the same.

Please let me know in case you face any issues.

Thanks
Pranav
